version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - FMCSA_API_KEY=${FMCSA_API_KEY}
      - API_KEY=${API_KEY}
    volumes:
      - ./app:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"