# render.yaml
services:
  - type: web
    name: carrier-sales-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: FMCSA_API_KEY
        sync: false
      - key: API_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
    autoDeploy: true